---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2019-11-14T06:52:39Z"
    labels:
      app.kubernetes.io/instance: cacti
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: cacti
      app.kubernetes.io/version: "1.0"
      helm.sh/chart: cacti-1.2.6
      io.cattle.field/appId: cacti
    name: cacti
    namespace: cacti
    resourceVersion: "932589"
    selfLink: /api/v1/namespaces/cacti/services/cacti
    uid: 18b4cb0f-a648-4f3e-b40f-e57236fa3d61
  spec:
    clusterIP: 10.43.94.37
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    selector:
      app.kubernetes.io/instance: cacti
      app.kubernetes.io/name: cacti
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      field.cattle.io/creatorId: user-r5l6g
      field.cattle.io/publicEndpoints: '[{"nodeName":"c-knb6m:m-eb0a19179762","addresses":["192.168.1.136"],"port":8080,"protocol":"TCP","podName":"cacti:cacti-67f49c946c-674s8","allNodes":false}]'
    creationTimestamp: "2019-11-14T06:52:39Z"
    generation: 3
    labels:
      cattle.io/creator: norman
      io.cattle.field/appId: cacti
      workload.user.cattle.io/workloadselector: deployment-cacti-cacti
    name: cacti
    namespace: cacti
    resourceVersion: "932645"
    selfLink: /apis/apps/v1/namespaces/cacti/deployments/cacti
    uid: 445b5df6-4a1c-4374-9a7a-1a8a4604062b
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-cacti-cacti
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: "2019-11-14T05:50:23Z"
          field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"cacti-hostport","hostPort":8080,"kind":"HostPort","name":"80tcp80800","protocol":"TCP","sourcePort":8080}]]'
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: deployment-cacti-cacti
      spec:
        containers:
        - env:
          - name: DB_HOST
            value: cacti-db
          - name: DB_PASS
            value: mysql*()
          - name: DB_USER
            value: root
          - name: TZ
            value: Asia/Shanghai
          image: harbor.ddc.com/cacti/cacti
          imagePullPolicy: IfNotPresent
          name: cacti
          ports:
          - containerPort: 80
            hostPort: 8080
            name: 80tcp80800
            protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            capabilities: {}
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
          - mountPath: /cacti
            name: vol1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /opt/HTML/cacti
            type: ""
          name: vol1
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2019-11-14T06:52:39Z"
      lastUpdateTime: "2019-11-14T06:52:39Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2019-11-14T06:52:39Z"
      lastUpdateTime: "2019-11-14T06:52:42Z"
      message: ReplicaSet "cacti-67f49c946c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      field.cattle.io/creatorId: user-r5l6g
    creationTimestamp: "2019-11-14T06:52:39Z"
    generation: 1
    labels:
      cattle.io/creator: norman
      io.cattle.field/appId: cacti
      workload.user.cattle.io/workloadselector: deployment-cacti-cacti-db
    name: cacti-db
    namespace: cacti
    resourceVersion: "932639"
    selfLink: /apis/apps/v1/namespaces/cacti/deployments/cacti-db
    uid: 00270e9c-b2e2-452a-a652-b6632c51f229
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-cacti-cacti-db
    strategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: "2019-11-13T07:23:15Z"
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: deployment-cacti-cacti-db
      spec:
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: mysql*()
          image: harbor.ddc.com/cacti/percona
          imagePullPolicy: IfNotPresent
          name: cacti-db
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: vol1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /opt/DB/cacti
            type: ""
          name: vol1
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2019-11-14T06:52:39Z"
      lastUpdateTime: "2019-11-14T06:52:39Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2019-11-14T06:52:39Z"
      lastUpdateTime: "2019-11-14T06:52:42Z"
      message: ReplicaSet "cacti-db-6c747c98bf" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  data:
    release: H4sIAAAAAAAC/+xczY8cSVbX2OxqyOGwagQSw+WR7VWPm86sqv7ulHzwdHvHLezuorvHoxnLWFGZr6rCjozIiYis7tqa5sCfwGHviDOnWYkjCHFB4swNwYkT4oIQSFxQRGRmZX21255hmWGqD6WqyBcR7/v9IuPZ3o9iEmu68h93vL+98/57/l/daYXwCWrQfQSSZYzGRFPB4dOzJ9AZgsw5p7xnHiuEWKQp4YmKPAC8yoTU0D49enny8OmjB/c+ep13MNYMeqghE4mCIOAkRZWRGMFuCwEDn2RZaEglR40qpKJhqB5Ygo3Zh5QrTXhcEPgQCHilBM+I7j/wRyHVmKrnzRdhipokRJPQrHbt3zcsxn0B/jOqqIa+1lnUaLQ298Jm2Axb0X5zvwlaQK4QhiKXdel9D6CUxkgZdIW8JDKBe6W4YKZH+01v5Tfe/8t///rffvSTr//6n79+78OJX+s/OTbMM2YUlzHU+OG//pG3XdjA/1Er3Ax313/3ITxGlkLcJ1JDV0j4g0oBZ3cGrVd3W2Fz5T8/8H5TY5oxolE1Tk4vHp2H+kqv/NMH72bA0SgA2oXwGWG5UTTvSVQqRE46DBO4vrYUkvAewr2+UBqiBzPUZlwZWoAxdWhMU4warY9GZqN703M1MzRqNALkZr+o0RiN3FZ2Xbi+Ho0gHK/uyLzpr0yhWT8WXBPKFfgnIsG2kNqv2FUoBzTGUA8zdOsVzntyevToZfv07GLKe+uOa5g4Q4ZEYXhSjV5fTzuiyjAOzarWG3nBxLUPxe7KrER5zPIEwbceEHZzxsxOvpXz/hRjx+0ptsyi6p2Yq6JEaaJzFZIkMUZAO1b8qMVMESz3Cjaie5WiFuj8iSDJx4SZOJU36R0AjOtGcKwhJUPQ5DUCgS5eQkp5rlHZADC+XF8SjtsmVDsIZEAoMy4autXc3+cih5hwuCQ67tvZTk4Q3XoMrL21jdUghuDyjZZbG1vu/NHZs+PDOcazS91mzzdtNmHbtVFpUlbTVxlkxro0u16bMeyYy8jwMWUvK8jC+DpkudIoj9u3CLDbVofFfry4YMzqaayjm+rI9F5wff2dqyq1JLfyiw+83x5n/pd9ZBlKFeqMrfy3Nxo11mFA0wgUauhShsYGD9JcaRL3MYL1hjVkY917dJURntjoMMKY2DDfbdkJvYIugAS7lE+pNBg/IznTEB7aSVZ7pQ8YytMBSkkThK9Ay5zHsLtlv9L0PO926RX4wXgxI5/57rg7lEi0yQXlHsbph/BlThjtUkyMIi3fofcZutUtvTZ7GBkUdDAmRu9KpFiroU7aLkWWKCASgdGUakyMmXSfKvioM7SaODo5N7QmU5hkfj/0jrsgnae4RaogcLXajlENl5Qxk5xyZfhUJqHljBXcLlDsOKZLfdSqcfmw0mdJs5DgVgo3oVz+uGeZjx7c3qY1Pis9uFUmw6nidWL0rRnMJOW6C/5PVfBT5U+t5vZ9Gy9b9H3C+2pmNaEyQKkMlCLKmbbwE0fFSAfZQvNaGn+hMHVdu+/Pir2+AokZM9nP/30f/Jf+u8SSSFPBHYdqEYfuqVtifoaN4KYU6/WRpaHqN6yo82gLHVjixfk4gjkJuQoIp5yHWVbqZ+5ahaHcUjNTvoIvc6FxCjzOrpISTnqYBJ3hJE/nrrrBlK5Xfhl6vzNOzAlmTAxT5DockpSt/CIkGX1WMjZoebamRF4A9XGSZaoxaJnKQHkSwVG1igdQFp/IYh3CudC2kKioAD+1PSdFkTigbgO/te0X1DYFhjHRmqEhio3TC3mcRMa9ZSB32G5vAW2WdxiNH/EkE5RrFcHa85Fv8KgxmB/5cfCad3bTKA2w0yStg9bewd7upr/hV0jTj577rYPNsLW7H7bC1tau/2LDN2XQt0Vzw8+k0CIWzI/8i8O2bx4m5erGnyL7GezudbcP4oPt3TjoX2XJntmDMQP6lR91CVN4/WLNSmHlo4Jf0BSVJmkWgb/ZbB0ErVbQ2rpo7kY7zWhn/wunnx5ylJY+gu09O+RCpFT2jOIi4EKmhBfPL4V8bUBYaJRZU105rpBhbKeNzRY4meynXcbF3eRvC4bqgxKVyGWMlRf5B5t7W3sHThCFrPuE8tcRNEhGVaNwsUa1lGrYpWoeW4zY6TlNIiC7cbfVTDYD3GvtBttd7AadrZ0k2NyOt/bj5KC70yIe2DLp1JNJYRHnEZKEUY7nGAtzzoTdZrPg2eIgFUGr+O089DFVWsjhE1OTI2g1SxGcqgrVpgbXP5mwxrekb6Ul0dgblstKwRjlvU+zhGgc75WSq/Nc9jCCZn3sU16dR0q5AAwAi+CsvpB9UqaKSqiJ6F4Q4ZOOp+d58vZFc8d48ubWF35t1kwEm6OpidvnI7+o3yjbRfxt+AlX9WALzBHcRueGb762a4FqMpUf+Y/L4Q2fu5n7TR1nhqbpzwln57Pjha5fFHG6IFZ5zlj1nE0Z/1syf92FLRulYmpbmYw/qO8cFFF69PHLx6fnF/WDKAwMcCpiNUg682e1H56fz5uVDtWXbP2j+/NnfXr+6GzeLCmEnjPj4ot5xIcT/NKUGJ/uE9kRMkySOIxFWmSHupIq2nbOWFswGg8jOO6eCN2WqFyxKv+mM5j7c943weaEE0aw35zgt3S6yJ6JJh65HcbONvGwdLsILg7btSdlzlQRjK5r4wrjXFI9PBRc45WOJhYjjInLtqQDyrCHj1RMWFEhtMxxgjQmGelQRjWd2cIwVSyRzJkpkSSnnA3PhNA/owzVUGlMI7C1bJIy5w/VieCGcva50gmd5UyjTCm3XD9FpYwNie5H0Ehw0Kg9DJjo3TytMLthsU6ohzN7DgTLU3wqcj5t89SMFQxMu0hp2IFgrWo44arcuHjv8DMq1djfpMkWUpc0D9klGarqqYr7mOQM5YlduTjqBNWwt8gL6gasqeITSWJso6QiqQrc1tj/nNwTqcO6sZF30h+cBkSmG48vnj6ZowpXRHzfW6Ad99KnAIZlDTqbqrGGQ1orJwEwovSFJFzRMtneiInATnA17BbEqfOUOoqFPlGQUk7TPC0ZNVEyLN/fSSTKBNRTR1OK8LCUqUzTTl7wL2SO/kSlnST9VmUsS+vO1qyMBafnqIvzTg2Z+lZslccxKuVeZJQACZNpyU/wcrzWW8jdLlak3AWu6CiUA0w+mQWyJsUMz2YQ2OTv3KogqZP9ys8qb39UeRPI34s2t6JWaw7Ib/0fYPwSEtSKZH3oFkh/v7W9s739TZF+uakF+939Pezs7mEQx53dYJtgMzggyVbQ6m4lZGdnb3cbN7/vYL8U+P8B3q+ceqeG93/1+HmMbr8BhH76+fkfPnl5dnp6YUHxZ6dnR7cExjdB1wxlLDj5ZuB1Er1/y/BxFtvdGj/OgYU/UAA5ILLBaKdhveMHDySPPv4OwcjJqvsGGDlN/D2Bke8g461gZNIJduO97b34YL/T/c4gydY3ApIOMD6hSnsr//jj+n1m2Q5i35n/zY/f0JZS3V4ZVZwUN1g33Ja7y40xhMUrjdx8NTipg5qUrB27jbx6ka7uQMa72bvtspbO3niUdyohfAWUJ8Zxt8cNLJdU92ckq2EARzkDCsxULT4nKbPr8tmFixsNV4cXaNC123gA2sGAWr/OIsoy7VR5qDan1vlTZijbrVO7axnPKfirMqREfVLqNhz/vqnVx9Quhm/gfIIpx7vbw/YTzbBmL++9eiqtZdz5/UxjaV3mHXcojf86JH6NPJlM1FC2AZ0scKo5pO71l+FygqtKI/M1tfIXd+vxVbZm2Pj607tTd1LO+YsLrvnOf2MvyjtFQ4kXXfKZ038ybiOpvTYM7I+59GW/SpHTiOyhnlHevBeDTsiCaPIc8k5XovMn3nzTufJnd717Y3tpVNp9BrHgHGOTCZz1/uvOXOu1RTLHcv6bTBdM7eG/Y2abyVd+eTHcF+K1H4Hdp6hgle2nTwnlgeCyhyUmKxB+J1fDjrgqD+iugTGC52uGdO1FMU5kT0UAz9feJPYN/U52sSkceIIDlJ7/9+97f/f+KhwVvRL2WOJa1dwe3ipc9KkCqoDA5w+fPgm6QqZEa0xsU44hOMKYEYkwIJKaaqaKlraMmFoOlGvhWoYqZwg9r6ithwb2mkLqOa1YRjOhqDlOR8B7lBsNadKLTKF3VT9bdN7xquPQuU2+KoLnL7x6s4fFjNNNJnbQK5Q2DuCqH6yIV/sq3ytysu0UdsV7fOCou0wJkFdhOmhcTo8ZUWos4SyhZiogsXV5XSCbWtEqq4DtRQjwiqQZw5CJmJQnBpf3jQKK4mi+mm0gmKhVEysEmilHVNtttbrZmLOZN32CXIXPEHKVE4PpJBrHNhmcC238wsQJ7Q6r7pxqtm1M0QIYkgG6/iXbcRQLrmIqcsdW3Bc0xqqX0h7xnYcSpoSJEIMZ0TYy8RiLhiZlDogguDmtUym4fWHkYAujWlunWh2zsmFwad9sb1C3sUoIx13jw5AIuCR8QpLatJw7aV3TcleYY7LDnqvAKDckJHmVK/s8NRtwNNmDyOGGlV9iKqz0CHEu2RA65jylgHQ1Slgbq3otLBZN6dhGcZZH0Go20+J3iqmNotbm/lNaiPhljuq2MzwuEjyvXpeMrj1PC1Yg58K1SLdLOTVH3dG1t/4vd7wPQpMmaY8LiSv/cGcV2iZbSG6zghuGyz5y6OSUJZT3ICPxa9IzWaFINirPbH0E1UfGoMdEx708o7y3ARIZ0XSA1sFr44Qn3ipw7Lk28Y8yiV16hYmz8+/dD+GUsyEIbmcaliBDae0SeuHR+ctzLSR6q1B0GT07PIeESuWFPaob9tOx74Wdn8uG/SwH+r2G+Sh/qgFvjBcyuCnPbLpU3nqoLjNvPeyQ1956qNPMW/9jbxWeEWl8HI6PHikvzKR4hbH2QpogaTg6KV554UDFIsGG5+97u0YthNma4xJVEc6uYcWzwMCs4oaz4OfbCTvw1v980wuCwFuFc+tKxUuhxnxg5b0lrCoP6vW3cosAx/hQP9Vw5U6L9t8QvBF4jBe5oXnKb4VNfwFRvTfqgjKGcgrGTVeBKdRWXeH+76Kzm+Sc1sbN5p1q5/KWzVzLZq5lM9eymWvZzLVs5lo2cy2buZbNXMtmrmUz17KZa9nMtWzmWjZzLZu5ls1cy2auZTPXsplr2cy1bOb6wTRzbf7Jr3m/5QSd6iZYudsWyYfr02/VF3c3+L+8+zbdDXM39b/vVyrfuW4K965+v7mwNWL9vV/ff+9j9x9a/U8AAAD//wnRCcVcTAAA
  kind: ConfigMap
  metadata:
    creationTimestamp: "2019-11-14T06:52:39Z"
    labels:
      MODIFIED_AT: "1573714359"
      NAME: cacti
      OWNER: TILLER
      STATUS: DEPLOYED
      VERSION: "1"
    name: cacti.v1
    namespace: cacti
    resourceVersion: "932593"
    selfLink: /api/v1/namespaces/cacti/configmaps/cacti.v1
    uid: 4a10f5e0-1377-4de2-93ae-c4c0412eae7f
kind: List
