apiVersion: v1                         #chart的API版本, 总是"v1",[必选]
name: mode                       #chart的名称,[必选]
version: 0.0.1                       #chart的版本，这个版本必须必要遵循SemVer 2标准,[必选]
#kubeVersion: 1.15.3                    #kubernetes的版本,遵循SemVer标准,[可选]
description: helm chart for mode      #chart模板的简介描述,[可选]
keywords:                              #关于此项目关键字列表,[可选]
  - mode
  - cms
  - blog
  - http
  - web
  - application
  - php
home: https://github.com/weicoll           #此项目的URL主页地址,[可选]
sources: https://github.com/weicoll/charts #此项目源代码的URL地址,[可选]
icon: file://mode.png    #此项目图标路径：SVG或者png格式,[可选]
maintainers:                                  #维护人员信息,[可选]
  - email: 254306040@qq.com              #维护人员邮箱,[可选]      
    name: weicoll                          #维护人员姓名,[可选]
    url: http://www.weicoll.com           #维护人员网址,[可选]
engine: gotpl                                 #模板引擎,[可选, 默认gotpl]
appVersion: 4.9.8                             #此包含的应用程序的版本
#tillerVersion: 2.14.3                         #此版本需要请求的tiller的版本,[可选]
